// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ywRSJUzdTUhnVH2e8V0mLwkQnHE1hTQ',
    appId: '1:800228398325:web:b9017fc340ae2db80021bc',
    messagingSenderId: '800228398325',
    projectId: 'perfectbudget-1ede1',
    authDomain: 'perfectbudget-1ede1.firebaseapp.com',
    storageBucket: 'perfectbudget-1ede1.appspot.com',
    measurementId: 'G-PS2EJNPXXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQ9M22gs8fqo_GaEIeZ-hDWV4FOF73tg',
    appId: '1:800228398325:android:7a109cd382e0796e0021bc',
    messagingSenderId: '800228398325',
    projectId: 'perfectbudget-1ede1',
    storageBucket: 'perfectbudget-1ede1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwQCDIu33FLu8OYAlZBR0QQsmPJY4aEs',
    appId: '1:800228398325:ios:c0f5bfafe0f0c6a30021bc',
    messagingSenderId: '800228398325',
    projectId: 'perfectbudget-1ede1',
    storageBucket: 'perfectbudget-1ede1.appspot.com',
    androidClientId: '800228398325-tgbthqhh6kkcsulq87rgbbu8mr4hflot.apps.googleusercontent.com',
    iosClientId: '800228398325-qt2ece03fc7l4uhb7kavtckt7d0qfn03.apps.googleusercontent.com',
    iosBundleId: 'dev.timistudio.monsey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwQCDIu33FLu8OYAlZBR0QQsmPJY4aEs',
    appId: '1:800228398325:ios:c0f5bfafe0f0c6a30021bc',
    messagingSenderId: '800228398325',
    projectId: 'perfectbudget-1ede1',
    storageBucket: 'perfectbudget-1ede1.appspot.com',
    androidClientId: '800228398325-tgbthqhh6kkcsulq87rgbbu8mr4hflot.apps.googleusercontent.com',
    iosClientId: '800228398325-qt2ece03fc7l4uhb7kavtckt7d0qfn03.apps.googleusercontent.com',
    iosBundleId: 'dev.timistudio.monsey',
  );
}
